const { chromium, webkit } = require('/Users/shuyukie/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(__dirname, 'output'); fs.mkdirSync(OUT, {recursive:true});
const ORIGIN = process.env.TEST_ORIGIN || 'http://127.0.0.1:8768';
const FIELDS = require('../parser.js').FIELDS;
let browser, debugPage;
(async () => {
 browser = await chromium.launch({channel:'chrome', headless:true});
 const context = await browser.newContext({viewport:{width:430,height:932},deviceScaleFactor:1,hasTouch:true,isMobile:true,acceptDownloads:true});
 const page = await context.newPage(); debugPage = page;
 const errors = [], requests = [];
 page.on('pageerror', e => errors.push(e.message));
 context.on('request', r => requests.push({url:r.url(),method:r.method()}));
 await page.goto(ORIGIN); await page.locator('#take-photo').waitFor();
 await page.waitForFunction(() => !document.querySelector('#take-photo').disabled);
 await page.evaluate(() => navigator.serviceWorker.ready);
 await page.screenshot({path:path.join(OUT,'home-iphone.png'),fullPage:true,animations:'disabled'});
 for (const width of [320,390,430]) { await page.setViewportSize({width,height:932}); assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `overflow at ${width}`); }
 await page.setViewportSize({width:430,height:932});
 const png = await page.evaluate(() => {
   const c = document.createElement('canvas'); c.width=1800;c.height=2500;
   const x = c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,c.width,c.height);x.fillStyle='#111';
   x.font='bold 65px "Hiragino Sans",sans-serif'; x.fillText('2026年9月 給与明細',130,130);
   x.font='48px "Hiragino Sans",sans-serif';
   const lines=[['支給年月','2026年9月'],['就業日数','20'],['出勤日数','20'],['欠勤日数','0'],['勤務時間','160'],['有休日数','1'],['残業時間','10'],['基本給','150,000'],['役職手当','5,000'],['通勤交通費','4,876'],['支給合計','159,876'],['健康保険','8,000'],['介護保険','1,000'],['厚生年金','15,000'],['雇用保険','689'],['所得税','4,000'],['住民税','10,000'],['控除合計','38,689'],['振込支給額','121,187'],['現金支給額','0']];
   lines.forEach((a,i)=>{x.fillText(a[0],130,280+i*100);x.fillText(a[1],730,280+i*100);});
   return c.toDataURL('image/png').split(',')[1];
 });
 fs.writeFileSync(path.join(OUT,'synthetic-payslip.png'),Buffer.from(png,'base64'));
 await page.evaluate(() => { const create = Tesseract.createWorker; Tesseract.createWorker = async (...args) => { const w = await create(...args), recognize = w.recognize; w.recognize = async (...args) => { const result = await recognize(...args); window.testOCR = result.data; return result; }; return w; }; });
 await page.locator('#photo-input').setInputFiles(path.join(OUT,'synthetic-payslip.png'));
 await page.locator('#review:not([hidden])').waitFor({timeout:160000});
 const result = await page.locator('#review-form input').evaluateAll(els => Object.fromEntries(els.map(e=>[e.name,e.value])));
 fs.writeFileSync(path.join(OUT,'ocr-raw.json'),JSON.stringify(await page.evaluate(()=>window.testOCR),null,2));
 fs.writeFileSync(path.join(OUT,'ocr-result.json'),JSON.stringify(result,null,2)); console.log('Actual browser OCR:', JSON.stringify(result));
 assert.equal(result.month,'2026-09');
 assert.equal(result.basePay,'150,000');assert.equal(result.gross,'159,876');assert.equal(result.deductions,'38,689');assert.equal(result.net,'121,187');
 await page.screenshot({path:path.join(OUT,'review-iphone.png'),fullPage:true,animations:'disabled'});
 await page.locator('#save-record').click(); await page.locator('#saved:not([hidden])').waitFor();
 assert.match(await page.locator('#month-comment').textContent(),/121,187円/);
 assert(await page.locator('.confetti').count() >= 20);
 await page.waitForTimeout(3000); assert.equal(await page.locator('.confetti').count(),0);
 await page.locator('#saved [data-go="history"]').click();assert.equal(await page.locator('.record-card').count(),1);
 await page.locator('.record-card').click();await page.locator('#edit-record').click();
 await page.locator('#field-basePay').fill('151000');await page.locator('#save-record').click();await page.locator('#saved:not([hidden])').waitFor();
 await page.reload();await page.waitForFunction(()=>!document.querySelector('#take-photo').disabled);
 await page.locator('#home [data-go="history"]').click();assert.equal(await page.locator('.record-card').count(),1);
 await page.locator('.record-card').click();assert.match(await page.locator('#detail-content').textContent(),/151,000円/);
 await page.locator('#home-button').click();await page.locator('#home [data-go="graphs"]').click();
 assert.match(await page.locator('#graph-content').textContent(),/121,187円/);assert.equal(await page.locator('.chart-line').count(),3);
 await page.screenshot({path:path.join(OUT,'graph-iphone.png'),fullPage:true,animations:'disabled'});
 await page.locator('#home-button').click();await page.locator('#home [data-go="backup"]').click();
 const downloadPromise=page.waitForEvent('download');await page.locator('#export-backup').click();const download=await downloadPromise;
 const backupPath=path.join(OUT,'test-backup.json');await download.saveAs(backupPath);
 const backup=JSON.parse(fs.readFileSync(backupPath));assert.equal(backup.records.length,1);assert.match(backup.records[0].image,/^data:image\/webp/);
 const size=Buffer.from(backup.records[0].image.split(',')[1],'base64').length;
 assert(size<500000,`compressed bytes ${size}`);
 const dims=await page.evaluate(src=>new Promise(resolve=>{const i=new Image();i.onload=()=>resolve([i.width,i.height]);i.src=src;}),backup.records[0].image);
 assert.equal(Math.max(...dims),2000);console.log('Compressed image:',size,'bytes',dims);
 await page.locator('#backup-input').setInputFiles(backupPath);await page.waitForFunction(()=>document.querySelector('#backup-status').textContent.includes('重複'));
 // Round-trip restore in a fresh browser context, then dedup and atomic bad-file rejection.
 const restoredContext=await browser.newContext({viewport:{width:430,height:932},acceptDownloads:true});const restored=await restoredContext.newPage();await restored.goto(ORIGIN);await restored.waitForFunction(()=>!document.querySelector('#take-photo').disabled);
 await restored.locator('#home [data-go="backup"]').click();restored.once('dialog', d=>d.accept());await restored.locator('#backup-input').setInputFiles(backupPath);await restored.waitForFunction(()=>document.querySelector('#backup-status').textContent.includes('1件の明細を復元'));
 await restored.locator('#backup-input').setInputFiles(backupPath);await restored.waitForFunction(()=>document.querySelector('#backup-status').textContent.includes('重複'));
 const bad={...backup,records:[{...backup.records[0],id:'new-good',month:'2026-08'},{...backup.records[0],id:'new-bad',month:'oops'}]};
 await restored.locator('#backup-input').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await restored.waitForFunction(()=>document.querySelector('#backup-status').textContent.includes('何も変更していません'));
 await restored.locator('#home-button').click();await restored.locator('#home [data-go="history"]').click();assert.equal(await restored.locator('.record-card').count(),1);
 await restored.locator('.record-card').click();restored.once('dialog',d=>d.dismiss());await restored.locator('#delete-record').click();assert(await restored.locator('#detail').isVisible());
 restored.once('dialog',d=>d.accept());await restored.locator('#delete-record').click();await restored.locator('.empty').waitFor();assert.equal(await restored.locator('.record-card').count(),0);
 await restoredContext.close();
 // Persist across a closed tab, and load / recognize fully offline after first use.
 await page.close();const offline=await context.newPage();await offline.goto(ORIGIN);await offline.waitForFunction(()=>!document.querySelector('#take-photo').disabled);
 await context.setOffline(true);await offline.reload();await offline.waitForFunction(()=>!document.querySelector('#take-photo').disabled);
 await offline.locator('#home [data-go="history"]').click();assert.equal(await offline.locator('.record-card').count(),1);
 await offline.locator('#home-button').click();await offline.locator('#photo-input').setInputFiles(path.join(OUT,'synthetic-payslip.png'));await offline.locator('#review:not([hidden])').waitFor({timeout:160000});assert.equal(await offline.locator('#field-net').inputValue(),'121,187');
 const network=requests.filter(r=>/^https?:/.test(r.url));assert(network.every(r=>new URL(r.url).origin === new URL(ORIGIN).origin),'external request');assert(network.every(r=>r.method==='GET'),'upload request');
 assert.deepEqual(errors,[]);console.log('PASS: real OCR, correction, save, animation, history, reload/closed tab, graphs, compressed WebP, backup round trip, dedup, malformed atomic restore, cancel/delete, 320/390/430 layout, offline OCR, no external requests.');
 await browser.close();
})().catch(async e=>{console.error(e);if(debugPage&&!debugPage.isClosed()){console.log('Failure state:',await debugPage.evaluate(()=>({notice:document.querySelector('#notice').textContent,visible:[...document.querySelectorAll('.screen')].filter(e=>!e.hidden).map(e=>e.id),invalid:[...document.querySelectorAll('input:invalid')].map(e=>({id:e.id,value:e.value,message:e.validationMessage})),saveDisabled:document.querySelector('#save-record').disabled})));await debugPage.screenshot({path:path.join(OUT,'failure.png'),fullPage:true,animations:'disabled'});}if(browser)await browser.close();process.exitCode=1;});
